data:
  timepoints:
  - T1
  - T2
  - T3
  data_config: Patient
  save_dir: results/cfg_2/submodels
  result_dir: results/cfg_2/model_analysis
  processed_data: data/prep/prince/20240903_totalData.rds
  sample_metadata: data/prep/prince/20240903_metadata_full.csv
training:
  mode: regression
